---
- name: Create DHCP options for VPC 
  ec2_vpc_dhcp_option:
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_create.vpc.id }}"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    domain_name: internal.example.com
    inherit_existing: False
    delete_old: False
    tags:
      Name: "dhcp_options_{{ company }}"
      Environment: "vpc_dhcp_options_{{ aws_environment }}"
  when: dns_primary is defined
  register: create_dhcp_options
